Fix doctests
Account for renaming of the types to follow Pascal case rules

Exception: `ANSIByteStrings` constructor function was not renamed
previously. Keeping it for now to not cause breakage